basePath: /api/v1
definitions:
  controllers.ApiError:
    properties:
      error:
        type: string
    type: object
  controllers.CreateOrderResponse:
    properties:
      address:
        type: string
      contractAddress:
        type: string
      orderId:
        type: string
      tokenId:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: These APIs allow the client to order items from the vendor
  license:
    name: MIT
    url: https://github.com/bdunton9323/blockchain-playground/blob/main/LICENSE
  title: Vendor API
  version: "1.0"
paths:
  /order:
    post:
      consumes:
      - application/json
      description: Places an order that can later be delivered
      parameters:
      - description: The item to order
        in: query
        name: itemId
        required: true
        type: string
      - description: the Ethereum address of the user who can accept the delivery
        in: query
        name: buyerAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CreateOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ApiError'
      summary: ping example
      tags:
      - order
swagger: "2.0"
